config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "user_registrations" }

  resources :users
  resources :posts do
  resources :comments
end # Makes comments resources are a subset of posts.

  get 'simple_pages/design'
  get 'simple_pages/photography'
  get 'simple_pages/recipes'
  resources :posts
  get 'simple_pages/about'
  get 'simple_pages/posts'
  get 'simple_pages/hireme'
  get 'simple_pages/index'
  get 'simple_pages/contact'
  root 'simple_pages#landing_page'
  post 'simple_pages/thank_you'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def landing_page
    @featured_post = Post.first
    @posts = Post.all
    @design_post=Post.where(theme: "Design")
    @photography_post=Post.where(theme: "Photography")
    @recipe_post=Post.where(theme: "Recipes")
  end

  def design
    @design_post=Post.where(theme: "Design")
  end

  def photography
    @photography_post=Post.where(theme: "Photography")
  end

  def recipes
    @recipe_post=Post.where(theme: "Recipes")
  end

  def thank_you
  @name = params[:name]
  @email = params[:email]
  @message = params[:message]
  ActionMailer::Base.mail(from: @email,
      to: 'julia@julia-hofmann.com',
      subject: "A new contact form message from #{@name}",
      body: @message).deliver_now
  end
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/simple_pages/_articles.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 col-sm-12 main-bar">
          <h3>Newest post</h3>
        <div class="row">
          <% @posts.first(3).each do |post| %>
          <div class="col-lg-4 col-md-4 col-sm-12 theme-image">
            <%= image_tag(post.image_url, class: "img img-fluid") %>
          </div><!-- /theme-image -->
          <div class="col-lg-8 col-md-8 col-sm-12">
            <div class="theme-category">
              <h6><a href="#"><%= post.theme %></h6></a>
            </div><!-- /theme-category -->
            <div class="theme-title">
              <h2><%= link_to post.name, post %></h2></a>
            </div><!-- /theme-title -->
            <div class="post-text">
              <p><%= post.description.first(200) %><%= link_to '(...)', post %></p>
            </div><!-- /post-text -->
            <div class="post-manage">
              <%= link_to 'Show', post %> / <%= link_to 'Edit', edit_post_path(post) %> / <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div><!-- /post-manage -->
          </div><!-- /col-lg-8 col-sm-12 -->
          <% end %>
        </div><!-- /row -->
    </div><!-- /main-bar -->
    <%= render 'shared/sidebar' %>
  </div><!-- /row -->
</div><!-- /posts-content -->

app/views/simple_pages/_design.html.erb
<div class="container-fluid">
  <h3>Design</h3>
  <div class="row image-row">
    <% @design_post.first(3).each do |post| %>
    <div class="col-lg-4 col-md-6 col-sm-12 theme-image">
      <div class="image-container">
        <%= link_to post do %>
        <div class="portfolio-image"><%= image_tag(post.image_url, class: "img img-fluid") %></div>
      <% end %>
      </div>
    </div><!-- /col-lg-8 col-sm-12 -->
    <% end %>
  </div><!-- /row -->
</div><!-- /container-fluid -->

app/views/simple_pages/_footer.html.erb
<div class="footer-content">
  <p class="footer-text">© 2018 by <%= link_to "Design in China 设计在中国", root_path, class:"footer-em" %></p>
  <ul class="footer-nav">
    <li class="footer-text"><a href="http://www.chinadesign.com">www.chinadesign.com</a></li>
    <li class="footer-text">contact</li>
    <li class="footer-text">terms</li>
    <li class="footer-text">privacy</li>
  </ul>
</div>

app/views/simple_pages/_header.html.erb
<%= link_to root_path do %>
<div class="logo"><%= image_tag 'Logo.designinchina.svg', class: "img-fluid", alt: 'logo' %></div>
<% end %>

<ul class=search-nav>
<li class="search-nav">
<%= form_with(url: posts_path, method: 'get', local: true, class: "back-ground") do |form| %>
<%= form.text_field :q, id: 'q', value: params[:q], class: "search_field" %>
<%= form.button'<i class="fa fa-search back-ground" aria-hidden="true"></i>'.html_safe, class:"my-2 my-sm-0 search_button back-ground", id: "register-button" %>
<% end %>
</li>
<% if user_signed_in? %>
<li class="login-link"><%= link_to('Logout', destroy_user_session_path, method: :delete, class: "login-link") %></li>
<% else %>
<li class="login-link"><%= link_to('Login', new_user_session_path, class: "login-link")%></li>
<% end %>
</li>
</ul>

<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light main-navigation">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li><%= link_to "Design", simple_pages_design_path %></li>
      <li><%= link_to "Photography", simple_pages_photography_path %></li>
      <li><%= link_to "Recipes", simple_pages_recipes_path %></li>
      <li><%= link_to "About", simple_pages_about_path %></li>
      <li><%= link_to "Hire me", simple_pages_hireme_path %></li>
      <li><%= link_to "Contact", simple_pages_contact_path %></li>
    </ul>
  </div>
</nav>

app/views/simple_pages/_photography.html.erb
<div class="container-fluid">
  <h3>Photography</h3>
  <div class="row image-row">
    <% @photography_post.first(3).each do |post| %>
    <div class="col-lg-4 col-md-6 col-sm-12 theme-image">
      <div class="image-container">
      <%= link_to post do %>
      <div class="portfolio-image"><%= image_tag(post.image_url, class: "img img-fluid") %></div>
      <% end %>
    </div>
    </div><!-- /col-lg-8 col-sm-12 -->
    <% end %>
  </div><!-- /row -->
</div><!-- /container-fluid -->

app/views/simple_pages/_recipes.html.erb
<div class="container-fluid">
  <h3>Recipes</h3>
  <div class="row image-row">
    <% @recipe_post.first(3).each do |post| %>
    <div class="col-lg-4 col-md-6 col-sm-12 theme-image">
      <div class="image-container">
        <%= link_to post do %>
        <div class="portfolio-image"><%= image_tag(post.image_url, class: "img img-fluid") %></div>
      <% end %>
      </div>
    </div><!-- /col-lg-8 col-sm-12 -->
    <% end %>
  </div><!-- /row -->
</div><!-- /container-fluid -->

app/views/simple_pages/about.html.erb
<div class="container-fluid">
  <h3>About</h3>
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-12 about-container">
      <%= image_tag 'about.270x270.jpg', class: "img img-fluid contact-img" %>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12">
      <p><em>Design in China 设计在中国</em> is a blog about Design, photography and food in China. Having lived in Beijing for over 10 years I call this place my home. </br> Beeing a designer and a photographer I want to share all things new and traditional in this area. China is not a place where we would look for great design in the first place. But I believe that there is a great potential. Chinese characters are beatiful and visually diverse. There are traditional elements and then there are minority styles. There are colorful patterns of southern China, there are nomadic styles from tibetan and mongolian areas.
      </br></br>So why is this blog also about chinese food? Simply because I love it! And I think, like design, it doesn't have the reputation that it deserves yet. There is a unbelievable variety in dishes, tastes and ingredients. I have been thinking about writing a chinese book for some time. So this is a first start to share some recipes with you :).</br> To see my own work in Design and photography please visit <a href="http://www.julia-hofmann.com" target="_blank">www.julia-hofmann.com</a>
  </div>
</div>
</div>

app/views/simple_pages/design.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-10 col-sm-12">
      <div class="container-fluid">
          <h3>Design</h3>
        <div class="row">
          <% @design_post.each do |post| %>
          <div class="col-lg-4 col-md-4 col-sm-12 theme-image">
            <%= image_tag(post.image_url, class: "img img-fluid") %>
          </div><!-- /theme-image -->
          <div class="col-lg-8 col-md-8 col-sm-12 post-content">
            <div class="theme-category">
              <h6><a href="#"><%= post.theme %></h6></a>
            </div><!-- /theme-category -->
            <div class="theme-title">
              <h2><a href="#"><%= post.name %></h2></a>
            </div><!-- /theme-title -->
            <div class="post-text">
              <p><%= post.description.first(200) %><%= link_to '(...)', post %></p>
            </div><!-- /post-text -->
            <div class="post-manage">
              <%= link_to 'Show', post %> / <%= link_to 'Edit', edit_post_path(post) %> / <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div><!-- /post-manage -->
          </div><!-- /col-lg-8 col-sm-12 -->
          <% end %>
        </div><!-- /row -->
      </div><!-- /container-fluid -->
    </div><!-- /main-bar -->
  <%= render 'shared/sidebar' %>
  </div><!-- /row -->
<div class="post-new">
  <%= link_to 'Create new post', new_post_path, class: "form_label btn btn-light message-button", id:"contact-button" %>
</div><!-- /post-new -->
</div><!-- /posts-content -->
</div>

app/views/simple_pages/hireme.html.erb
<div class="container-fluid">
  <h3>Hire me!</h3>
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-12 hireme-image">
      <a href="http://www.julia-hofmann.com" target="_blank">  <%= image_tag 'JuliaHofmann-hireme.jpg', class: "img-fluid"%></a>
    </div>
  <div class="col-lg-6 col-md-6 col-sm-12">
      <p class="hireme-text">I am a designer for web and print as well as an art photographer based between Berlin and Beijing. Contact me for projects connected with China and Asia. In aliquam sem fringilla ut morbi tincidunt augue interdum velit. Eu consequat ac felis donec et odio pellentesque diam volutpat. Ut etiam sit amet nisl purus in mollis. Sit amet purus gravida quis. Tristique magna sit amet purus gravida quis blandit. Ullamcorper a lacus vestibulum sed arcu non odio euismod lacinia. Amet est placerat in egestas erat imperdiet sed. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Velit sed ullamcorper morbi tincidunt. Viverra orci sagittis eu volutpat odio facilisis mauris sit. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Faucibus nisl tincidunt eget nullam. Lorem sed risus ultricies tristique. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero.
    Diam donec adipiscing tristique risus nec feugiat in fermentum. Gravida neque convallis a cras. Cras pulvinar mattis nunc sed blandit libero volutpat. Tellus pellentesque eu tincidunt tortor. Imperdiet massa tincidunt nunc pulvinar sapien. Viverra nibh cras pulvinar mattis nunc sed blandit. Augue interdum velit euismod in pellentesque massa placerat duis.
  </br> Have a look at my portfolio: <a href="http://www.julia-hofmann.com" target="_blank">www.julia-hofmann.com</a></p>
</div>


</div>

app/views/simple_pages/landing_page.html.erb
  <%= render 'simple_pages/carousel' %>
  <%= render 'simple_pages/articles' %>
  <%= render 'simple_pages/design' %>
  <%= render 'simple_pages/photography' %>
  <%= render 'simple_pages/recipes' %>

app/views/simple_pages/photography.html.erb
<div class="container-fluid posts-content">
  <div class="row">
    <div class="col-lg-10 col-sm-12 main-bar">
      <div class="container-fluid">
          <h3>Photography</h3>
        <div class="row">
          <% @photography_post.each do |post| %>
          <div class="col-lg-4 col-md-4 col-sm-12 theme-image">
            <%= image_tag(post.image_url, class: "img img-fluid") %>
          </div><!-- /theme-image -->
          <div class="col-lg-8 col-md-8 col-sm-12 post-content">
            <div class="theme-category">
              <h6><a href="#"><%= post.theme %></h6></a>
            </div><!-- /theme-category -->
            <div class="theme-title">
              <h2><a href="#"><%= post.name %></h2></a>
            </div><!-- /theme-title -->
            <div class="post-text">
              <p><%= post.description.first(200) %><%= link_to '(...)', post %></p>
            </div><!-- /post-text -->
            <div class="post-manage">
              <%= link_to 'Show', post %> / <%= link_to 'Edit', edit_post_path(post) %> / <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div><!-- /post-manage -->
          </div><!-- /col-lg-8 col-sm-12 -->
          <% end %>
        </div><!-- /row -->
      </div><!-- /container-fluid -->
    </div><!-- /main-bar -->
    <%= render 'shared/sidebar' %>
  </div><!-- /row -->
</div><!-- /posts-content -->
<div class="post-new">
  <%= link_to 'Create new post', new_post_path, class: "form_label btn btn-light message-button", id:"contact-button" %>
</div><!-- /post-new -->
</div>

app/views/simple_pages/posts.html.erb
<h3>Posts</h3>
<p>Find me in app/views/simple_pages/posts.html.erb</p>

app/views/simple_pages/recipes.html.erb
<div class="container-fluid posts-content">
  <div class="row">
    <div class="col-lg-10 col-sm-12 main-bar">
      <div class="container-fluid">
          <h3>Recipes</h3>
        <div class="row">
          <% @recipe_post.each do |post| %>
          <div class="col-lg-4 col-md-4 col-sm-12 theme-image">
            <%= image_tag(post.image_url, class: "img img-fluid") %>
          </div><!-- /theme-image -->
          <div class="col-lg-8 col-md-8 col-sm-12 post-content">
            <div class="theme-category">
              <h6><a href="#"><%= post.theme %></h6></a>
            </div><!-- /theme-category -->
            <div class="theme-title">
              <h2><a href="#"><%= post.name %></h2></a>
            </div><!-- /theme-title -->
            <div class="post-text">
              <p><%= post.description.first(200) %><%= link_to '(...)', post %></p>
            </div><!-- /post-text -->
            <div class="post-manage">
              <%= link_to 'Show', post %> / <%= link_to 'Edit', edit_post_path(post) %> / <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div><!-- /post-manage -->
          </div><!-- /col-lg-8 col-sm-12 -->
          <% end %>
        </div><!-- /row -->
      </div><!-- /container-fluid -->
    </div><!-- /main-bar -->
    <%= render 'shared/sidebar' %>
  </div><!-- /row -->
</div><!-- /posts-content -->
<div class="post-new">
  <%= link_to 'Create new post', new_post_path, class: "form_label btn btn-light message-button", id:"contact-button" %>
</div><!-- /post-new -->
</div>

app/views/simple_pages/thank_you.html.erb
<div class="message-page">
    <p>Thank you. We have received your message and will respond as soon as possible.</p>
  </div><!-- / panel-body -->