config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "user_registrations" }

  resources :users
  resources :posts do
  resources :comments
end # Makes comments resources are a subset of posts.

  get 'simple_pages/design'
  get 'simple_pages/photography'
  get 'simple_pages/recipes'
  resources :posts
  get 'simple_pages/about'
  get 'simple_pages/posts'
  get 'simple_pages/hireme'
  get 'simple_pages/index'
  get 'simple_pages/contact'
  root 'simple_pages#landing_page'
  post 'simple_pages/thank_you'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  validates :name, presence: true #Adds validation to the Post model。
  validates :theme, presence: true #Adds validation to the Post model。
  validates :description, presence: true #Adds validation to the Post model。

  has_many :comments
  def self.search(search_term)
  Post.where("name LIKE ?", "%#{search_term}%")
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if params[:q]
      search_term = params[:q]
      @posts = Post.search(search_term)
    else
      @posts = Post.all
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.order("created_at DESC")
    @comments = @post.comments.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to '/simple_pages/index' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :description, :image_url, :theme)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.erb
<div class="container-fluid">
  <h2 id="comment-header">Comments</h2>
    <% @comments.each do |comment| %>
</div>
<div class="post-comment">
  <div class="postcomment-user"><%= comment.user.first_name %> </div>
  <div class="postcomment-date"><%= "#{time_ago_in_words(comment.created_at)} ago" %></div>
  <div class="postcomment-text"><%= comment.body %></div>
  <% if signed_in? && current_user.admin? %>
    <%= link_to ('<span class="fas fa-trash"></span>').html_safe, post_comment_path(comment.post, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
</div>
    <% end %>

</div>

app/views/posts/_form.html.erb
<div class="container-fluid">
  <%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="message-field">
  <div class="form-group">
    <%= form.label :name, class:"contact-label" %>
    <%= form.text_field :name, class: "form-control", placeholder: "Post name"  %>
  </div>

  <div class="form-group">
    <%= form.label :description, class:"contact-label" %>
    <%= form.text_area :description, class: "form-control", placeholder: "Post description", rows: 5, cols:40   %>
  </div>

  <div class="form-group">
    <%= form.label :image_url, class:"contact-label" %>
    <%= form.text_field :image_url, class: "form-control", placeholder: "Image_url"  %>
  </div>

  <div class="form-group">
    <%= form.label :theme, class:"contact-label" %>
    <%= form.text_field :theme, class: "form-control", placeholder: "Post theme" %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', id:"contact-button", class:"form_label btn btn-light message-button" %>
  </div>
<% end %>
</div>
</div>

app/views/posts/_new_comment.html.erb
<div class="comment-box">
<% if signed_in? %>
  <h2 id="newcomment-header">Write a comment</h2>
  <%= form_for([@post, @post.comments.build]) do |f| %>
      <div class="comment-box">
        <div class="form-group">
          <%= f.text_area :body, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Submit", class: "form_label btn btn-light message-button", id:"contact-button" %>
        </div >
      </div >
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-10 col-sm-12 main-bar">
      <div class="container-fluid">
        <div class="post-category">
          <h5>New posts</h5>
        </div><!-- /post-category -->
        <div class="row">
          <% @posts.each do |post| %>
          <div class="col-lg-4 col-md-4 col-sm-12 theme-image">
            <%= image_tag(post.image_url, class: "img img-fluid") %>
          </div><!-- /theme-image -->
          <div class="col-lg-8 col-md-8 col-sm-12 post-content">
            <div class="theme-category">
              <h6><a href="#"><%= post.theme %></h6></a>
            </div><!-- /theme-category -->
            <div class="theme-title">
              <h2><a href="#"><%= post.name %></h2></a>
            </div><!-- /theme-title -->
            <div class="post-text">
              <p><%= post.description %></p>
            </div><!-- /post-text -->
            <div class="post-manage">
              <%= link_to 'Show', post %> / <%= link_to 'Edit', edit_post_path(post) %> / <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div><!-- /post-manage -->
          </div><!-- /col-lg-8 col-sm-12 -->
          <% end %>
        </div><!-- /row -->
      </div><!-- /container-fluid -->
    </div><!-- /main-bar -->
    <div class="col-lg-2 col-sm-12">
      <div class="side-bar">
        <div class="sidebar-topic">
          <h5>About</h5>
          <p>Design in China is a blog about Design, photography and food in China. Having lived in Beijing for over 10 years I call this place my home. Beeing a designer and a photographer I would like to share all things new and traditional in this area. Plus I am a great Chinese food-lover, and want to sahre some of my favourite recipes and new encounterings with you!</p>
          <%= image_tag 'about.270x270.jpg', class: "img img-fluid" %>
        </div><!-- /sidebar-topic -->
        <div class="sidebar-topic">
          <h5>Social Links</h5>
          <div class="sidebar-social">
            <div class="sidebar-icon">
              <%= image_tag('instagram.svg', class: "img-fluid") %>
            </div><!-- /sidebar-social -->
            <div class="sidebar-icon">
              <%= image_tag('linkedin.svg', class: "img-fluid") %>
            </div><!-- /sidebar-social -->
            <div class="sidebar-icon">
              <%= image_tag('pinterest.svg', class: "img-fluid") %>
            </div><!-- /sidebar-social -->
          </div>
        </div><!-- /sidebar-topic -->
    </div><!-- /col-lg-2 col-sm-12 -->
  </div><!-- /row -->
</div><!-- /posts-content -->
<div class="post-new">
  <%= link_to 'New Post', new_post_path %>
</div><!-- /post-new -->

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="post-name">
      <h2><%= @post.name %></h2>
  <p class="post-info">
    <%= @post.theme %> |
    <%= @post.created_at %>
  </p>
</div>
<div class="post-image">
  <%= image_tag(@post.image_url, class: "img-fluid") if @post.image_url%>
</div>

<div class="post-name">
  <p class="post-info">
    <%= link_to 'Edit', edit_post_path(@post) %> |
    <%= link_to 'Back', post_path %>
  </p>
</div>

<div class="post-description">
  <%= @post.description %>
</div>

<hr class="line-dotted"/>
  <%= render 'comments' %>
  <p class="comment-pagination"><%= will_paginate @comments %></p>
  <%= render 'new_comment' %>
</div>
</div>